### PR TITLE
Update roman-numerals.php

### PR DESCRIPTION
**Pull request by jacobmc**
Does this seem acceptable?

(not sure why the 5's and 10's are all out of sync with everything else)

### CODE REVIEW

**Comment by kjohnson** [comment]
What if I tested XIV?

**Comment by jacobmc** [comment]
Touché

**Comment by kjohnson** [comment]
More where that came from :-P

**Comment by jacobmc** [comment]
I imagine you could somehow set it up to automatically add the value of the keys together but I'm not sure how one would go about processing it. For instance, if the user inputs 'XIV' how would we program it to know to add 10 and 4 rather than 10, 1, and 5? I'm not sure how you could separate 1 character without separating all of them.

**Comment by kjohnson** [comment]
If you are looking to separate out the characters, take a look at PHP's [str_split()](http://php.net/str_split).

**Comment by jacobmc** [comment]
I was going to go that route but it doesn't make sense to separate all the characters and add the values together because then 'XIV' would become 16 instead of 14.  is there a php function for searching a string for an existing key within an array? I know I could use strpos() if i was checking substrings against another existing string, but I don't think that would work with keys within an array.

**Comment by jacobmc** [comment]
The only thing I can imagine to do is to make an array item for every possible number, which I did for numbers 1-20, then every 10 (30, 40, etc) until 100, then every 100 (200, 300, etc) until 1000. I tried to come up with a function to separate the string and recognize various numeral combinations and add the values together, but I had no success with the limited knowledge I possess. This was the best I could come up with.

**Comment by jacobmc** [comment]
Also, this function should accept both lowercase and uppercase numerals as it passes all $numerals data through the strtoupper() function before continuing the rest of the function.

**Comment by kjohnson** [comment]
The goal is to avoid hard coding every possible complete combination, as the possibilities are infinite.

Also, there are many ways to complete this code kata.

If you are wanting to compare against a list, consider (logically, the PHP comes later) a finite list could be used.

**Comment by kjohnson** [comment]
Almost. What if I ran `XXXXIV` or `L`?

I see where you are going with the comparisons after the loop, but could you use the loop to avoid hard coding a maximum length of 4 characters?

**Comment by jacobmc** [comment]
XXXXIV is not a possible roman numeral lol (it would be XLIV), but I see what you mean. I'll work on that solution.

**Comment by kjohnson** [comment]
I was testing you :stuck_out_tongue: , but yeah, you see what I mean.

The hardest part about programming is doing things programatically. @klhall1987

**Comment by jacobmc** [comment]
Every time I think I'm done...

**Comment by kjohnson** [comment]
Life Lesson: In modern software development, nothing is ever 'done'.

You can thank the internet for that...

**Pull request closed without merging**
